# You should just need to run this to do a release of both crates:
# $ cargo release <minor|patch>

pre-release-commit-message = "Release {{version}}"
tag-message = "Release `{{crate_name}}` {{version}}"
tag-prefix = "rust-gpu"
allow-branch = ["main"]
shared-version = true
