[toolchain]
channel = "nightly-2025-11-13"
components = ["rust-src", "rustc-dev", "llvm-tools"]
# commit_hash = 2286e5d224b3413484cf4f398a9f078487e7b49d

# Whenever changing the nightly channel, update the commit hash above, and
# change `REQUIRED_RUST_TOOLCHAIN` in `crates/rustc_codegen_spirv/build.rs` too.
