[toolchain]
channel = "nightly-2025-11-02"
components = ["rust-src", "rustc-dev", "llvm-tools"]
# commit_hash = bd3ac0330018c23b111bbee176f32c377be7b319

# Whenever changing the nightly channel, update the commit hash above, and
# change `REQUIRED_RUST_TOOLCHAIN` in `crates/rustc_codegen_spirv/build.rs` too.
