[toolchain]
channel = "nightly-2025-06-23"
components = ["rust-src", "rustc-dev", "llvm-tools"]
# commit_hash = be19eda0dc4c22c5cf5f1b48fd163acf9bd4b0a6

# Whenever changing the nightly channel, update the commit hash above, and
# change `REQUIRED_RUST_TOOLCHAIN` in `crates/rustc_codegen_spirv/build.rs` too.
