# this crate updates the changelog in the root of the repo
pre-release-replacements = [
	{ file = "../../CHANGELOG.md", search = "## \\[Unreleased\\]", replace = "## [{{version}}] - {{date}}" },
	{ file = "../../CHANGELOG.md", search = "\\[Unreleased\\]: https://github.com/rust-gpu/rust-gpu/compare/v\\d+.\\d+.\\d+...HEAD", replace = "[{{version}}]: https://github.com/rust-gpu/rust-gpu/releases/tag/{{tag_name}}" },
	{ file = "../../CHANGELOG.md", search = "<!-- next-header -->", replace = "<!-- next-header -->\n## [Unreleased]" },
	{ file = "../../CHANGELOG.md", search = "<!-- next-url -->", replace = "<!-- next-url -->\n[Unreleased]: https://github.com/rust-gpu/rust-gpu/compare/{{tag_name}}...HEAD" },
]
